Ver indicadores del IBEX 35 últimos 90 días:

http://localhost:8000/indicadores?symbol=%5EIBEX&days=90


Ver predicción de todos los modelos:

http://localhost:8000/predecir_ensemble?symbol=%5EIBEX&days=90


Obtener últimas noticias (últimos 7 días):

http://localhost:8000/noticias?q=IBEX+35+OR+Bolsa+de+Madrid&when=7d


http://localhost:8000/docs